-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 10:44:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kg_demo_movie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kg_demo_movie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kg_demo_movie` DEFAULT CHARACTER SET utf8mb4 ;
USE `kg_demo_movie` ;

-- -----------------------------------------------------
-- Table `kg_demo_movie`.`PERSON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kg_demo_movie`.`PERSON` (
  `person_id` INT NOT NULL,
  `person_birth_day` VARCHAR(45) NULL,
  `person_death_day` VARCHAR(45) NULL,
  `person_name` VARCHAR(45) NULL,
  `person_english_name` VARCHAR(45) NULL,
  `person_biography` VARCHAR(2000) NULL,
  `person_birth_place` VARCHAR(45) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kg_demo_movie`.`MOVIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kg_demo_movie`.`MOVIE` (
  `movie_id` INT NOT NULL,
  `movie_title` VARCHAR(100) NULL,
  `movie_introduction` VARCHAR(2000) NULL,
  `movie_rating` FLOAT NULL,
  `movie_release_date` VARCHAR(45) NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kg_demo_movie`.`PERSON_TO_MOVIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kg_demo_movie`.`PERSON_TO_MOVIE` (
  `person_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`person_id`, `movie_id`),
  INDEX `movie_id_idx` (`movie_id` ASC),
  CONSTRAINT `person_movie_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `kg_demo_movie`.`PERSON` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie_person_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `kg_demo_movie`.`MOVIE` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kg_demo_movie`.`GENRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kg_demo_movie`.`GENRE` (
  `genre_id` INT NOT NULL,
  `genre_name` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kg_demo_movie`.`MOVIE_TO_GENRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kg_demo_movie`.`MOVIE_TO_GENRE` (
  `movie_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `genre_id`),
  INDEX `genre_movie_id_idx` (`genre_id` ASC),
  CONSTRAINT `movie_genre_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `kg_demo_movie`.`MOVIE` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `genre_movie_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `kg_demo_movie`.`GENRE` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
